### ISSUE TITLE
Use Visual Testing

### ISSUE THREAD

**Issue by TAnas0** [hikaya-io/cypress-tests-activity#4]
Implement [Visual Testing in Cypress](https://docs.cypress.io/guides/tooling/visual-testing.html) using the [cypress-plugin-snapshots](https://github.com/meinaart/cypress-plugin-snapshots).

**Acceptance Criteria**
Provide a way of Visual Testing where screenshots of the pages or elements are compared to previous baselines.

**Comment by amosnjoroge** [comment]
PR merged
